{"uuid": "2adb41cc-3cbe-492c-8940-86a3de777523", "children": ["24894394-be36-41bb-978a-e0a8606ef691", "ac67f12f-d313-4c43-9e20-dfdefce6ee8e"], "befores": [{"name": "login", "status": "skipped", "statusDetails": {"message": "Skipped: ❌ Ошибка логина: Message: Поле ввода телефона недоступно\n\n", "trace": "  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/conftest.py\", line 438, in login\n    pytest.skip(f\"❌ Ошибка логина: {e}\")\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/_pytest/outcomes.py\", line 159, in skip\n    raise Skipped(msg=reason, allow_module_level=allow_module_level)\n"}, "start": 1759839860895, "stop": 1759839876334}], "start": 1759839860895, "stop": 1759839881348}